# Generated by Django 4.2.3 on 2023-07-13 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_manufacturer_and_model', models.CharField(blank=True, max_length=200)),
                ('image_capture_date', models.DateTimeField(blank=True, null=True)),
                ('shutter_speed', models.FloatField(blank=True, null=True)),
                ('exposure_time', models.FloatField(blank=True, null=True)),
                ('aperture_value', models.FloatField(blank=True, null=True)),
                ('iso_sensitivity', models.IntegerField(blank=True, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('metering_mode', models.CharField(blank=True, max_length=200)),
                ('flash_usage', models.BooleanField(blank=True, null=True)),
                ('image_resolution', models.CharField(blank=True, max_length=200)),
                ('image_orientation', models.CharField(blank=True, max_length=200)),
                ('lens_type', models.CharField(blank=True, max_length=200)),
                ('white_balance_setting', models.CharField(blank=True, max_length=200)),
                ('digital_zoom_ratio', models.FloatField(blank=True, null=True)),
                ('focal_length_in_35mm_film', models.IntegerField(blank=True, null=True)),
                ('scene_capture_type', models.CharField(blank=True, max_length=200)),
                ('gps_info_latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('gps_info_longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('gps_info_altitude', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exif_data', to='mainapp.submissions')),
            ],
        ),
    ]
