# Generated by Django 5.0.4 on 2024-05-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aperture_value', models.FloatField(blank=True, null=True)),
                ('brightness_value', models.FloatField(blank=True, null=True)),
                ('date_time_original', models.DateTimeField(blank=True, null=True)),
                ('exposure_bias_value', models.FloatField(blank=True, null=True)),
                ('exposure_program', models.IntegerField(blank=True, null=True)),
                ('exposure_time', models.FloatField(blank=True, null=True)),
                ('f_number', models.FloatField(blank=True, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('max_aperture_value', models.FloatField(blank=True, null=True)),
                ('metering_mode', models.IntegerField(blank=True, null=True)),
                ('shutter_speed_value', models.FloatField(blank=True, null=True)),
                ('gps_altitude', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('gps_altitude_ref', models.IntegerField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('gps_latitude_ref', models.CharField(blank=True, max_length=1, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('gps_longitude_ref', models.CharField(blank=True, max_length=1, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('lens_make', models.CharField(blank=True, max_length=255, null=True)),
                ('lens_model', models.CharField(blank=True, max_length=255, null=True)),
                ('exposure_time_star', models.FloatField(blank=True, null=True)),
                ('f_number_star', models.FloatField(blank=True, null=True)),
                ('iso_star', models.IntegerField(blank=True, null=True)),
                ('focal_length_star', models.FloatField(blank=True, null=True)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exif_data', to='mainapp.submissions')),
            ],
        ),
    ]
