# Generated by Django 4.2.3 on 2023-07-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exif',
            old_name='camera_manufacturer_and_model',
            new_name='datetimeoriginal',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='image_orientation',
            new_name='digitalzoomratio',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='image_resolution',
            new_name='exposuretime',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='lens_type',
            new_name='flash',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='metering_mode',
            new_name='fnumber',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='scene_capture_type',
            new_name='focallength',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='white_balance_setting',
            new_name='focallengthin35mmfilm',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='gps_info_altitude',
            new_name='gpsaltitude',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='gps_info_latitude',
            new_name='gpslatitude',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='gps_info_longitude',
            new_name='gpslongitude',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='aperture_value',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='digital_zoom_ratio',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='exposure_time',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='flash_usage',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='focal_length',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='focal_length_in_35mm_film',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='image_capture_date',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='iso_sensitivity',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='shutter_speed',
        ),
        migrations.AddField(
            model_name='exif',
            name='isospeedratings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='lensmodel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='lensspecification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='make',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='meteringmode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='orientation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='scenecapturetype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='whitebalance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='xresolution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exif',
            name='yresolution',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
