# Generated by Django 4.2.3 on 2023-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_camera_manufacturer_and_model_exif_datetimeoriginal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exif',
            name='datetimeoriginal',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='digitalzoomratio',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='exposuretime',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='flash',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='fnumber',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='focallength',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='focallengthin35mmfilm',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='gpsaltitude',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='gpslatitude',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='gpslongitude',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='isospeedratings',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='lensmodel',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='lensspecification',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='make',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='meteringmode',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='model',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='scenecapturetype',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='whitebalance',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='xresolution',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='yresolution',
        ),
        migrations.AddField(
            model_name='exif',
            name='exif_data',
            field=models.TextField(blank=True),
        ),
    ]
