# Generated by Django 4.2.3 on 2023-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_exif_datetimeoriginal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exif',
            name='exif_data',
        ),
        migrations.AddField(
            model_name='exif',
            name='aperture_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='camera_manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='camera_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='digital_zoom_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='exposure_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='flash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='focal_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='focal_length_in_35mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='iso_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='lens_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='metering_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='orientation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='resolution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='scene_capture_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exif',
            name='shutter_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='white_balance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
