# Generated by Django 4.2.3 on 2023-07-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_exif_exif_data_exif_aperture_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exif',
            old_name='datetime',
            new_name='date_time_original',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='focal_length_in_35mm',
            new_name='exposure_program',
        ),
        migrations.RenameField(
            model_name='exif',
            old_name='iso_speed',
            new_name='gps_altitude_ref',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='camera_manufacturer',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='camera_model',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='digital_zoom_ratio',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='flash',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='focal_length',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='lens_type',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='scene_capture_type',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='shutter_speed',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='exif',
            name='white_balance',
        ),
        migrations.AddField(
            model_name='exif',
            name='brightness_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='exposure_bias_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='exposure_time_star',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='f_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='f_number_star',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='focal_length_star',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='gps_latitude_ref',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='gps_longitude_ref',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='iso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='iso_star',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='lens_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='lens_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='max_aperture_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exif',
            name='shutter_speed_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='aperture_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='exposure_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='metering_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
