# Generated by Django 4.2.3 on 2023-07-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_datetime_exif_date_time_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exif',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exif_data', to='mainapp.submissions'),
        ),
    ]
