# Generated by Django 4.2.3 on 2023-07-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_exif_gps_altitude_alter_exif_gps_altitude_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exif',
            name='gps_altitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_altitude_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_latitude_ref',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_longitude_ref',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
