# Generated by Django 4.2.3 on 2023-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_exif_gps_altitude_alter_exif_gps_altitude_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exif',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exif',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
